apiVersion: v2
name: asya-test-actors
description: A Helm chart for deploying Asya test AsyncActor resources
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
- asya
- actor
- async
- kubernetes
maintainers:
- name: Asya Team
