apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: rabbitmq
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  username: {{ .Values.auth.username }}
  password: {{ .Values.auth.password }}
