{{- if or .Values.postgresql.enabled .Values.externalDatabase.host }}
{{- if not .Values.externalDatabase.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "asya-gateway.fullname" . }}-db
  labels:
    {{- include "asya-gateway.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  {{- if .Values.postgresql.enabled }}
  database-url: >-
    postgresql://{{ include "asya-gateway.databaseUsername" . }}:{{ .Values.postgresql.auth.password }}@{{ include "asya-gateway.databaseHost" . }}:{{ include "asya-gateway.databasePort" . }}/{{ include "asya-gateway.databaseName" . }}?sslmode=disable
  password: {{ .Values.postgresql.auth.password | quote }}
  {{- else if .Values.externalDatabase.host }}
  database-url: >-
    postgresql://{{ include "asya-gateway.databaseUsername" . }}:{{ .Values.externalDatabase.password }}@{{ include "asya-gateway.databaseHost" . }}:{{ include "asya-gateway.databasePort" . }}/{{ include "asya-gateway.databaseName" . }}?sslmode=disable
  password: {{ .Values.externalDatabase.password | quote }}
  {{- end }}
{{- end }}
{{- end }}
