{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: s3
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  access-key-id: {{ .Values.auth.accessKey | quote }}
  secret-access-key: {{ .Values.auth.secretKey | quote }}
{{- end }}
